version: "3"

services:
  database:
    container_name: postgres-db
    image: "postgres:alpine"
    tty: true
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    container_name: pg-admin
    image: "dpage/pgadmin4:latest"
    depends_on:
      - database
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  redis:
    container_name: redis
    image: "redis:alpine"
    tty: true
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data
    ports:
      - "${REDIS_PORT}:6379"

  redis-commander:
    container_name: redis-commander
    image: "rediscommander/redis-commander:latest"
    depends_on:
      - redis
    ports:
      - "${REDISCOMMANDER_PORT}:8081"
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDISCOMMANDER_USER}
      HTTP_PASSWORD: ${REDISCOMMANDER_PASSWORD}

volumes:
  pgdata:
  redisdata:
